[workspace]
authors = ["Matt Haberland <mhaberla@calpoly.edu>"]
channels = ["conda-forge"]
name = "monorepo"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
pre-commit = ">=4.2.0,<5"
ruff = ">=0.12.1,<0.13"
mypy = ">=1.16.1,<2"
