[workspace]
authors = ["Matt Haberland <mhaberla@calpoly.edu>"]
channels = ["conda-forge"]
name = "monorepo"
platforms = ["win-64", "linux-64", "osx-64"]
version = "0.1.0"

[tasks]
# This is one of the benefits of pixi? no need for `spin` or `dev.py`?

[tasks.build_docs]
description = "Build the Sphinx documentation"
cmd = "sphinx-build -b html -E docs/ _build_docs/"

[tasks.serve_docs]
description = "Run the documentation server"
cmd = "python -m http.server --directory _build_docs"

[dependencies]
python = ">=3.10,<4.0"
pre-commit = ">=4.2.0,<5"
ruff = ">=0.12.1,<0.13"
mypy = ">=1.16.1,<2"
pytest = ">=8.4.1,<9"
sphinx = ">=8.2.3,<9"
pydata-sphinx-theme = ">=0.16.0,<1.0"
numpydoc = ">=1.8.0,<2.0"
jupyterlite-sphinx = ">=0.20, <1.0"
jupyterlite-pyodide-kernel = ">=0.6, <1.0"
jupyterlab = ">=4.0, <5.0"
jupytext = ">=1.17, <2.0"

# Runtime dependencies for package1
numpy = ">=2.0, <3.0"
flit = ">=3.11.0,<4"
keyring = ">=25.6.0,<26"
myst-parser = ">=4.0.1,<5"
python-semantic-release = ">=10.2.0,<11"

[pypi-dependencies]
monorepo-package1 = { path = "./package1/", editable = true }
monorepo-package2 = { path = "./package2/", editable = true }
