name: documentation

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read         # for checkout
  pages: write           # needed by deploy-pages
  id-token: write        # needed by configure-pages

jobs:
  docs:
    environment:
      # this can be simpler if we don't need to preview docs on PRs
      name: ${{ github.event_name == 'push' && 'github-pages' || '' }}
      url:  ${{ github.event_name == 'push' && steps.deploy-pages.outputs.page_url }}
        
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.44.0

      - name: Install dependencies
        run: |
          pixi install

      - name: Build documentation
        run: |
          pixi run sphinx-build docs _build

      # We can delete all the `if` stuff below and just use official GH actions
      # if we don't need to preview the docs on PRs.
      # ----------------------
      # PR preview
      # ----------------------
      - name: Deploy PR preview
        if: github.event_name == 'pull_request'
        uses: rossjrw/pr-preview-action@v1.6.1
        with:
          token: ${{ secrets.PREVIEW_TOKEN }}
          source-dir: ./_build
          preview-branch: gh-pages
          umbrella-dir: pr-preview

      # ----------------------
      # Production deploy
      # ----------------------
      - name: Upload Pages artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build

      - name: Configure GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: deploy-pages
        uses: actions/deploy-pages@v4
