name: documentation

on:
  # I tried to get PR preview docs working, but couldn't, so for now
  # we only get to see the built docs on pushes to main
  push:
    branches:
      - main

permissions:
  contents: read         # for checkout
  pages: write           # needed by deploy-pages
  id-token: write        # needed by configure-pages

jobs:
  docs:
    environment:
      name: github-pages
        
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.44.0

      - name: Install dependencies
        run: |
          pixi install

      - name: Build documentation
        run: |
          pixi run sphinx-build docs _build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4
