name: documentation

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read         # for checkout
  pages: write           # needed by deploy-pages
  id-token: write        # needed by configure-pages

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.44.0

      - name: Install dependencies
        run: |
          pixi install

      - name: Build documentation
        run: |
          pixi run sphinx-build docs _build

      # Only on pushes to main: upload the built HTML
      - name: Upload Pages artifact
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: _build

      # Configure the Pages site (branch, folder, etc.)
      - name: Configure GitHub Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/configure-pages@v2

      # Deploy the uploaded artifact to the gh-pages branch
      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/deploy-pages@v1