name: Tests + coverage

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read         # for checkout
  pages: write           # needed by deploy-pages
  id-token: write        # needed by configure-pages

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.44.0

      - name: Install dependencies
        run: pixi install

      - name: Run tests
        run: pixi run pytest --cov --cov-branch --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
